# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 4
        vb.memory = "2048"
    end

    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y devscripts debhelper tree vim
        sudo apt-get install -y cmake mesa-common-dev libgl1-mesa-dev
        sudo apt-get install -y texlive-latex-extra texlive-latex-recommended
    SHELL
end
